import { createHash } from 'node:crypto'
import { writeFile } from 'node:fs/promises'
import { BrowserWindow, app, clipboard, nativeImage, type ClipboardItem } from 'electron'
import { FILE_LIST, pathsFromFileList } from './clipboard-files'
import { recordClipboardEntry } from './db/clipboard'
import { describeStoredFile, removeStoredFile, reserveStorage } from './files'
import type { ClipboardKind } from './db/schema'

/**
 * The clipboard history: everything copied while a task was in front.
 *
 * Electron has no clipboard-change event, and there is no native module here to
 * read the pasteboard's own change counter, so copying is caught by *sampling*
 * — reading the clipboard on a timer and noticing when what it holds is not
 * what it held last time. That is the whole mechanism, and it has one honest
 * consequence: two copies inside a single interval collapse into the second.
 *
 * What it buys in exchange is uniformity. A copy out of a page, a terminal, a
 * extension's view or a file view all end up on the same system pasteboard, so one
 * timer catches every one of them without any of those surfaces having to
 * report anything — and without the app having to intercept a keystroke that a
 * native `WebContentsView` would never have shown it anyway.
 */

/**
 * How often the pasteboard is read. Fast enough that a copy is filed before the
 * hand has left the keys, slow enough that the cost is invisible — and it only
 * runs at all while one of the app's own windows has focus.
 */
const POLL_MS = 500

/**
 * The largest image worth keeping, in bytes. Past this the copy is still
 * recorded, with its size and dimensions and no picture: the history saying
 * "an image, and a big one" is worth more than it silently saying nothing,
 * which would read as the capture having failed.
 */
const MAX_IMAGE_BYTES = 10 * 1024 * 1024

/** The same, for text. A copy past this is recorded as having happened. */
const MAX_TEXT_BYTES = 4 * 1024 * 1024

/**
 * Pasteboard types that mean "this is not for you".
 *
 * The first three are the macOS convention password managers and the like mark
 * their writes with, and 1Password, Keychain Access and the system's own
 * one-time-code fill all set at least one. Honouring them is the difference
 * between a clipboard history and a plaintext record of every password the user
 * copied today, so it is checked before anything is read, not after.
 *
 * The last is the Windows spelling of the same idea. Left in the list on every
 * platform because `clipboard.has` simply answers false for a type the
 * pasteboard has never heard of.
 *
 * None of them has a MIME type, so each is asked after as the raw platform
 * format Electron exposes under `electron application/osclipboard`.
 */
const PRIVATE_TYPES = [
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.TransientType',
  'org.nspasteboard.AutoGeneratedType',
  'ExcludeClipboardContentFromMonitorProcessing'
].map((format) => `electron application/osclipboard;format="${format}"`)

/**
 * What the clipboard held last time it was looked at, or null while the app is
 * not in front.
 *
 * Null is doing real work rather than standing in for "unknown". Losing focus
 * forgets the baseline, and the first tick after focus returns sets it again
 * *without recording* — which is exactly what capturing only while the app is
 * focused has to mean. Without that, coming back from a copy made in another
 * app would file that copy here, under whichever task happened to be open.
 *
 * It is also why nothing is recorded at launch: the first tick of all finds a
 * null baseline and sets it, so the history starts from the moment the app did
 * rather than with whatever had been sitting on the pasteboard since breakfast.
 */
let baseline: string | null = null

/**
 * Bumped whenever the baseline is set from outside a tick: focus leaving, or
 * the app writing the clipboard itself. Every read of the pasteboard is a
 * promise, so a tick can be half-way through when either happens, and one that
 * carried on would put back a baseline that is no longer true — filing the
 * app's own restore as a fresh copy, or a copy made in another app under
 * whichever task was open. A tick that sees this move gives up.
 */
let epoch = 0

/** Whether a tick is still reading, so the next one does not start over it. */
let ticking = false

let timer: NodeJS.Timeout | undefined

/**
 * Which task is in front, as the one side that knows tells it. The title comes
 * along because the panel draws it and would otherwise have to ask a second
 * question to get it.
 */
export type ClipboardTaskRef = {
  id: string
  /** Null for an untitled task, which is what a new one is. */
  title: string | null
}

/**
 * The task a copy belongs to: whichever one the window has selected. Pushed
 * from the renderer as it changes rather than read from the database, because
 * which task is selected is the window's own state and is not persisted
 * anywhere this side could look it up.
 *
 * Null before the workspace has loaded, and while it has nothing selected. A
 * copy made then is dropped — there is nowhere to file it.
 */
let activeTask: ClipboardTaskRef | null = null

/** Told by the renderer, every time the selected task or its name changes. */
export function setClipboardTask(task: ClipboardTaskRef | null): void {
  activeTask = task
}

/**
 * The task in front, for whoever needs to name it: the capture below, and the
 * panel, which opens onto it. Read back here rather than asked of the renderer
 * because the renderer is the side that pushed it, and asking would mean a
 * round trip through a window that may well have a page in front of it.
 */
export function clipboardTask(): ClipboardTaskRef | null {
  return activeTask
}

/** Whether any of the app's own windows currently has focus. */
function focused(): boolean {
  return BrowserWindow.getAllWindows().some((window) => !window.isDestroyed() && window.isFocused())
}

/** Whether whatever is on the pasteboard was marked as nobody else's business. */
async function concealed(): Promise<boolean> {
  const answers = await Promise.all(
    PRIVATE_TYPES.map((type) =>
      // A platform that rejects the format name outright rather than answering
      // false for it. Not a reason to stop capturing, and not a reason to treat
      // the content as concealed either.
      clipboard.has(type).catch(() => false)
    )
  )
  return answers.includes(true)
}

/**
 * One representation of the copy, as bytes, or null when the pasteboard does
 * not offer it. Every type asked for here resolves to a `Blob`; only the
 * bookmark format does not, and nothing here asks for that.
 */
async function payload(item: ClipboardItem | undefined, type: string): Promise<Buffer | null> {
  if (!item?.types.includes(type)) return null
  const blob = await item.getType(type)
  return blob instanceof Blob ? Buffer.from(await blob.arrayBuffer()) : null
}

/** The same, for a textual representation. Empty when it is not offered. */
async function payloadText(item: ClipboardItem | undefined, type: string): Promise<string> {
  return (await payload(item, type))?.toString('utf8') ?? ''
}

/** One copy, read off the pasteboard and ready to be written down. */
type Capture = {
  kind: ClipboardKind
  text: string
  html: string | null
  rtf: string | null
  /** The PNG, for an image small enough to keep. */
  png: Buffer | null
  width: number | null
  height: number | null
  size: number
}

/**
 * Everything on the pasteboard, in one read, or null when there is nothing
 * there worth recording.
 *
 * Every representation at once, because that is what the pasteboard actually
 * holds: one copy offered as plain text, as markup, as RTF and sometimes as a
 * picture, and picking one of them at capture would be deciding on the user's
 * behalf what they will want to paste later.
 */
async function read(): Promise<Capture | null> {
  // One copy is one item on every platform Electron supports; the array is the
  // W3C shape rather than something a desktop pasteboard ever fills.
  const [item] = await clipboard.read()

  // Files first: a copy of files offers their names as plain text too, and
  // filed as text it would be a list of names that pastes as nothing but words.
  const paths = pathsFromFileList(await payloadText(item, FILE_LIST))
  if (paths.length > 0) {
    const text = paths.join('\n')
    return {
      kind: 'files',
      text,
      html: null,
      rtf: null,
      png: null,
      width: null,
      height: null,
      size: Buffer.byteLength(text)
    }
  }

  const text = await clipboard.readText()
  const html = await payloadText(item, 'text/html')
  const rtf = await payloadText(item, 'text/rtf')

  // Chromium hands back the plain text as the HTML representation when the
  // source offered no markup of its own, which would make every ordinary copy
  // look like a rich one. What marks a genuine rich copy is markup that says
  // something the text does not.
  const markup = html && html !== text ? html : null

  if (text !== '') {
    const size = Buffer.byteLength(text)
    // Recorded as having happened, with nothing kept — the same shape an
    // oversized image takes, and read back the same way (see `isTruncated` in
    // src/renderer/src/lib/clipboard-entries.ts).
    if (size > MAX_TEXT_BYTES) {
      return {
        kind: 'text',
        text: '',
        html: null,
        rtf: null,
        png: null,
        width: null,
        height: null,
        size
      }
    }
    return {
      kind: markup ? 'rich-text' : 'text',
      text,
      html: markup,
      rtf: rtf === '' ? null : rtf,
      png: null,
      width: null,
      height: null,
      size
    }
  }

  const png = await payload(item, 'image/png')
  if (png === null || png.byteLength === 0) return null

  const { width, height } = nativeImage.createFromBuffer(png).getSize()

  return {
    kind: 'image',
    text: '',
    html: null,
    rtf: null,
    png: png.byteLength > MAX_IMAGE_BYTES ? null : png,
    width,
    height,
    size: png.byteLength
  }
}

/**
 * A short, stable stand-in for what the pasteboard holds, cheap enough to
 * compute twice a second.
 *
 * Hashed rather than kept verbatim, and that is not about size. The baseline
 * this produces is held in module state between ticks, so a signature that *was*
 * the copied text would leave the last thing copied sitting in memory — and the
 * last thing copied is sometimes the password this module refuses to write down
 * anywhere else. A digest answers the only question ever asked of it, which is
 * whether the pasteboard has changed since the last look.
 *
 * An image is hashed from its PNG, which is the only form the clipboard hands
 * one over in. Getting it can mean the platform encoding the picture, so that
 * read is the one costly thing this module does — and it happens only on the
 * ticks where an image is actually sitting on the pasteboard, which is rare and
 * short-lived.
 */
async function signature(): Promise<string | null> {
  const [item] = await clipboard.read()
  const formats = item?.types.join(',') ?? ''

  // Ahead of the text, which for files is only their names: two files of the
  // same name copied out of different folders are different copies.
  const files = await payload(item, FILE_LIST)
  if (files !== null) return digest(formats, files)

  const text = await clipboard.readText()
  if (text !== '') return digest(formats, Buffer.from(text))

  const png = await payload(item, 'image/png')
  if (png === null) return formats === '' ? null : digest(formats, EMPTY)

  return digest(formats, png)
}

const EMPTY = Buffer.alloc(0)

/** One digest over a label and some bytes, with a separator between the two. */
function digest(label: string, bytes: Buffer): string {
  return createHash('sha1').update(label).update(SEPARATOR).update(bytes).digest('hex')
}

/** Keeps a label ending in the bytes' first byte from colliding with the reverse. */
const SEPARATOR = Buffer.from([0])

/**
 * Re-reads the pasteboard and accepts what it finds as already seen.
 *
 * Called after the app itself puts something on the clipboard — restoring an
 * entry from the panel — so that the write does not come straight back as a
 * fresh copy. Without it, every restore would duplicate the entry it restored.
 */
export async function forgetClipboardChange(): Promise<void> {
  const current = ++epoch
  const seen = await signature()
  if (epoch === current) baseline = seen
}

/** Writes one capture down against the task that was in front when it happened. */
async function store(taskId: string, capture: Capture): Promise<void> {
  let storageKey: string | null = null
  let thumbnail: string | null = null

  if (capture.png) {
    // Into the app's own file store, the same place a dropped file and a
    // download go — so a copied picture is a file the app owns rather than
    // bytes held in a database row, and the panel can point an `<img>` at it
    // over the scheme that already serves the store.
    const slot = reserveStorage('clipboard.png')
    await writeFile(slot.path, capture.png)
    const stored = await describeStoredFile(slot.storageKey, 'clipboard')
    storageKey = stored.storageKey
    thumbnail = stored.thumbnail ?? null
  }

  const { orphaned } = await recordClipboardEntry({
    taskId,
    kind: capture.kind,
    text: capture.text,
    html: capture.html,
    rtf: capture.rtf,
    storageKey,
    thumbnail,
    width: capture.width,
    height: capture.height,
    size: capture.size
  })

  // Whatever the insert pushed off the end of the task took its picture with
  // it. The row is already gone, so nothing can name these files any more.
  for (const key of orphaned) void removeStoredFile(key)
}

/**
 * One look at the pasteboard.
 *
 * Deliberately does its own focus check rather than being started and stopped
 * by focus events: moving between the app's own windows — the launcher opening
 * over the main window, say — fires a blur and a focus in quick succession, and
 * a timer torn down and rebuilt on that pair would forget its baseline every
 * time the user pressed Cmd+T.
 */
async function tick(): Promise<void> {
  if (!focused()) {
    baseline = null
    return
  }

  if (ticking) return
  ticking = true
  try {
    await look()
  } finally {
    ticking = false
  }
}

async function look(): Promise<void> {
  const started = epoch
  const current = await signature()
  if (current === null || epoch !== started) return

  // The first look after the app came forward. What is on the pasteboard now
  // was put there before this was the app's business.
  if (baseline === null) {
    baseline = current
    return
  }

  if (current === baseline) return
  baseline = current

  if (await concealed()) return

  const task = activeTask
  if (task === null) return

  const capture = await read()
  if (capture && epoch === started) await store(task.id, capture)
}

export function startClipboardCapture(): void {
  if (timer) return

  // `setInterval` rather than the routines' run-then-wait, because a tick is
  // bounded work against local memory rather than a network round trip, and a
  // fixed rate is what makes the sampling interval mean what it says. The rare
  // tick that is still reading a large image when the next comes due is left
  // to finish; the next one simply skips.
  timer = setInterval(() => {
    void tick().catch((error) => {
      // Sampling is a background job with nobody watching it, and a failed tick
      // must not stop the next one — the same rule the routines follow.
      console.error('Failed to capture a clipboard change:', error)
    })
  }, POLL_MS)

  // Capturing must never be the reason the app is awake.
  timer.unref()

  app.on('browser-window-blur', onBlur)
}

/**
 * Forgets the baseline the moment focus leaves, rather than waiting for the
 * next tick to notice. Half a second is long enough to copy something in
 * another app, and a baseline that outlived the focus would let that copy be
 * filed here as though it had been made in the task.
 */
function onBlur(): void {
  // On the next turn, because the blur that comes of moving from one of the
  // app's own windows to another arrives before the matching focus.
  setImmediate(() => {
    if (focused()) return
    baseline = null
    epoch++
  })
}

export function stopClipboardCapture(): void {
  if (timer) clearInterval(timer)
  timer = undefined
  baseline = null
  epoch++
  app.off('browser-window-blur', onBlur)
}
