/**
 * Turning `:tada:` into 🎉.
 *
 * Slack serves the workspace's *custom* emoji and nothing else — standard ones
 * it expects the client to know — so this table is that knowledge. It is a
 * curated few hundred rather than the full Unicode set: the long tail of emoji
 * names is thousands of entries for a list that would be read once a year, and
 * a name that is not here falls back to being drawn as `:name:`, which is
 * legible and says plainly that we did not recognise it.
 *
 * Add to it freely. That is the intended way to maintain it.
 */

/** Slack's short name → the character. Aliases are listed separately below. */
const STANDARD: Record<string, string> = {
  // Reactions, which is most of what this is for
  '+1': '👍',
  '-1': '👎',
  thumbsup: '👍',
  thumbsdown: '👎',
  ok_hand: '👌',
  raised_hand: '✋',
  facepunch: '👊',
  fist: '✊',
  clap: '👏',
  raised_hands: '🙌',
  pray: '🙏',
  muscle: '💪',
  wave: '👋',
  handshake: '🤝',
  v: '✌️',
  crossed_fingers: '🤞',
  point_up: '☝️',
  point_down: '👇',
  point_left: '👈',
  point_right: '👉',
  eyes: '👀',
  brain: '🧠',
  fire: '🔥',
  tada: '🎉',
  confetti_ball: '🎊',
  sparkles: '✨',
  star: '⭐',
  star2: '🌟',
  zap: '⚡',
  boom: '💥',
  rocket: '🚀',
  ship: '🚢',
  trophy: '🏆',
  first_place_medal: '🥇',
  second_place_medal: '🥈',
  third_place_medal: '🥉',
  dart: '🎯',
  bulb: '💡',
  '100': '💯',
  heavy_check_mark: '✔️',
  white_check_mark: '✅',
  ballot_box_with_check: '☑️',
  x: '❌',
  heavy_multiplication_x: '✖️',
  warning: '⚠️',
  exclamation: '❗',
  question: '❓',
  grey_question: '❔',
  grey_exclamation: '❕',
  bangbang: '‼️',
  interrobang: '⁉️',
  no_entry: '⛔',
  no_entry_sign: '🚫',
  o: '⭕',
  heavy_plus_sign: '➕',
  heavy_minus_sign: '➖',
  recycle: '♻️',
  repeat: '🔁',
  arrows_counterclockwise: '🔄',
  arrow_up: '⬆️',
  arrow_down: '⬇️',
  arrow_left: '⬅️',
  arrow_right: '➡️',
  arrow_forward: '▶️',
  arrow_backward: '◀️',

  // Faces
  grinning: '😀',
  smiley: '😃',
  smile: '😄',
  grin: '😁',
  laughing: '😆',
  sweat_smile: '😅',
  joy: '😂',
  rofl: '🤣',
  slightly_smiling_face: '🙂',
  upside_down_face: '🙃',
  wink: '😉',
  blush: '😊',
  innocent: '😇',
  heart_eyes: '😍',
  kissing_heart: '😘',
  yum: '😋',
  stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜',
  zany_face: '🤪',
  money_mouth_face: '🤑',
  hugging_face: '🤗',
  thinking_face: '🤔',
  face_with_raised_eyebrow: '🤨',
  neutral_face: '😐',
  expressionless: '😑',
  no_mouth: '😶',
  smirk: '😏',
  unamused: '😒',
  roll_eyes: '🙄',
  grimacing: '😬',
  lying_face: '🤥',
  relieved: '😌',
  pensive: '😔',
  sleepy: '😪',
  sleeping: '😴',
  mask: '😷',
  face_with_thermometer: '🤒',
  nauseated_face: '🤢',
  sneezing_face: '🤧',
  hot_face: '🥵',
  cold_face: '🥶',
  woozy_face: '🥴',
  dizzy_face: '😵',
  exploding_head: '🤯',
  cowboy_hat_face: '🤠',
  partying_face: '🥳',
  sunglasses: '😎',
  nerd_face: '🤓',
  confused: '😕',
  worried: '😟',
  slightly_frowning_face: '🙁',
  frowning_face: '☹️',
  open_mouth: '😮',
  hushed: '😯',
  astonished: '😲',
  flushed: '😳',
  pleading_face: '🥺',
  fearful: '😨',
  cold_sweat: '😰',
  cry: '😢',
  sob: '😭',
  scream: '😱',
  confounded: '😖',
  persevere: '😣',
  disappointed: '😞',
  sweat: '😓',
  weary: '😩',
  tired_face: '😫',
  yawning_face: '🥱',
  triumph: '😤',
  rage: '😡',
  angry: '😠',
  face_with_symbols_on_mouth: '🤬',
  smiling_imp: '😈',
  imp: '👿',
  skull: '💀',
  skull_and_crossbones: '☠️',
  poop: '💩',
  clown_face: '🤡',
  ghost: '👻',
  alien: '👽',
  robot_face: '🤖',
  see_no_evil: '🙈',
  hear_no_evil: '🙉',
  speak_no_evil: '🙊',
  shrug: '🤷',
  face_palm: '🤦',

  // Hearts and marks
  heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  black_heart: '🖤',
  white_heart: '🤍',
  brown_heart: '🤎',
  broken_heart: '💔',
  two_hearts: '💕',
  sparkling_heart: '💖',
  heartpulse: '💗',
  heartbeat: '💓',
  anger: '💢',
  dizzy: '💫',
  sweat_drops: '💦',
  dash: '💨',
  zzz: '💤',
  speech_balloon: '💬',
  thought_balloon: '💭',

  // Work
  hammer: '🔨',
  wrench: '🔧',
  hammer_and_wrench: '🛠️',
  gear: '⚙️',
  nut_and_bolt: '🔩',
  lock: '🔒',
  unlock: '🔓',
  key: '🔑',
  mag: '🔍',
  mag_right: '🔎',
  link: '🔗',
  paperclip: '📎',
  pushpin: '📌',
  round_pushpin: '📍',
  memo: '📝',
  page_facing_up: '📄',
  clipboard: '📋',
  calendar: '📅',
  chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉',
  bar_chart: '📊',
  books: '📚',
  book: '📖',
  bookmark: '🔖',
  label: '🏷️',
  moneybag: '💰',
  dollar: '💵',
  credit_card: '💳',
  gem: '💎',
  package: '📦',
  email: '📧',
  envelope: '✉️',
  inbox_tray: '📥',
  outbox_tray: '📤',
  bell: '🔔',
  no_bell: '🔕',
  loudspeaker: '📢',
  mega: '📣',
  hourglass: '⌛',
  hourglass_flowing_sand: '⏳',
  watch: '⌚',
  alarm_clock: '⏰',
  stopwatch: '⏱️',
  computer: '💻',
  desktop_computer: '🖥️',
  keyboard: '⌨️',
  iphone: '📱',
  floppy_disk: '💾',
  bug: '🐛',
  construction: '🚧',
  rotating_light: '🚨',
  sos: '🆘',
  new: '🆕',
  ok: '🆗',
  up: '🆙',
  cool: '🆒',
  free: '🆓',

  // Weather and nature
  snowflake: '❄️',
  rainbow: '🌈',
  sunny: '☀️',
  sun_with_face: '🌞',
  cloud: '☁️',
  ocean: '🌊',
  droplet: '💧',
  earth_americas: '🌎',
  crescent_moon: '🌙',
  seedling: '🌱',
  herb: '🌿',
  four_leaf_clover: '🍀',
  maple_leaf: '🍁',
  mushroom: '🍄',
  cactus: '🌵',
  palm_tree: '🌴',
  sunflower: '🌻',
  rose: '🌹',
  tulip: '🌷',

  // Food and drink
  coffee: '☕',
  tea: '🍵',
  beer: '🍺',
  beers: '🍻',
  wine_glass: '🍷',
  cocktail: '🍸',
  champagne: '🍾',
  clinking_glasses: '🥂',
  pizza: '🍕',
  hamburger: '🍔',
  fries: '🍟',
  taco: '🌮',
  burrito: '🌯',
  cake: '🍰',
  birthday: '🎂',
  cookie: '🍪',
  doughnut: '🍩',
  popcorn: '🍿',
  apple: '🍎',
  banana: '🍌',
  watermelon: '🍉',
  strawberry: '🍓',
  avocado: '🥑',
  bread: '🍞',
  cheese: '🧀',
  salt: '🧂',
  honey_pot: '🍯',
  ice_cream: '🍨',
  lollipop: '🍭',

  // Animals
  dog: '🐶',
  cat: '🐱',
  mouse: '🐭',
  bear: '🐻',
  panda_face: '🐼',
  fox_face: '🦊',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  cow: '🐮',
  pig: '🐷',
  frog: '🐸',
  monkey_face: '🐵',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  duck: '🦆',
  eagle: '🦅',
  owl: '🦉',
  wolf: '🐺',
  unicorn: '🦄',
  bee: '🐝',
  butterfly: '🦋',
  snail: '🐌',
  lady_beetle: '🐞',
  ant: '🐜',
  spider: '🕷️',
  turtle: '🐢',
  snake: '🐍',
  dragon: '🐉',
  whale: '🐳',
  dolphin: '🐬',
  fish: '🐟',
  octopus: '🐙',
  shark: '🦈',
  crab: '🦀',
  sheep: '🐑',
  rabbit: '🐰',
  horse: '🐴',
  elephant: '🐘',
  hedgehog: '🦔'
}

/**
 * Names that mean the same as another. Kept apart from the table above so that
 * the canonical name is obvious, and so a correction only has to be made once.
 */
const ALIASES: Record<string, string> = {
  satisfied: 'laughing',
  simple_smile: 'slightly_smiling_face',
  face_with_rolling_eyes: 'roll_eyes',
  thinking: 'thinking_face',
  hankey: 'poop',
  shit: 'poop',
  poo: 'poop',
  robot: 'robot_face',
  collision: 'boom',
  pencil: 'memo',
  date: 'calendar',
  punch: 'facepunch',
  pout: 'rage',
  person_shrugging: 'shrug',
  'man-shrugging': 'shrug',
  'woman-shrugging': 'shrug',
  'person-shrugging': 'shrug',
  facepalm: 'face_palm',
  'man-facepalming': 'face_palm',
  'woman-facepalming': 'face_palm',
  heavy_exclamation_mark: 'exclamation',
  negative_squared_cross_mark: 'x',
  raised_back_of_hand: 'raised_hand',
  fist_raised: 'fist',
  white_frowning_face: 'frowning_face',
  thumbs_up: 'thumbsup',
  thumbs_down: 'thumbsdown'
}

/**
 * The five Fitzpatrick modifiers, by the number Slack writes after
 * `::skin-tone-`. Tone 1 is the yellow default and has no modifier at all,
 * which is why the table starts at 2.
 */
const SKIN_TONES: Record<string, string> = {
  '2': '\u{1F3FB}',
  '3': '\u{1F3FC}',
  '4': '\u{1F3FD}',
  '5': '\u{1F3FE}',
  '6': '\u{1F3FF}'
}

/**
 * The character for a Slack emoji name, or null when it is not one this table
 * knows — which includes every custom emoji, since those are pictures rather
 * than characters and are resolved against the workspace's own list instead.
 *
 * Skin tones arrive as a suffix (`wave::skin-tone-3`) and are applied here, so
 * callers only ever deal in whole names.
 */
export function standardEmoji(name: string): string | null {
  const [base, ...modifiers] = name.split('::')
  const canonical = ALIASES[base] ?? base
  const character = STANDARD[canonical]
  if (character === undefined) return null

  const tone = modifiers
    .map((modifier) => /^skin-tone-(\d)$/.exec(modifier)?.[1])
    .find((digit) => digit !== undefined)

  return tone !== undefined ? `${character}${SKIN_TONES[tone] ?? ''}` : character
}

/**
 * Names worth offering before the user has typed anything, for the reaction
 * picker. The ones a team actually reaches for, in the order they reach for
 * them, rather than the first entries of an alphabetical list.
 */
export const QUICK_REACTIONS = [
  '+1',
  'tada',
  'heart',
  'joy',
  'eyes',
  'white_check_mark',
  'rocket',
  'fire',
  'pray',
  'thinking_face',
  'clap',
  '100'
] as const

/** Every standard name, for the picker's search. */
export function standardEmojiNames(): string[] {
  return Object.keys(STANDARD)
}
